### ISSUE TITLE
log to console

### ISSUE THREAD

**Issue by nikhilpandey4** [T-Pham/UITextField-Navigation#8] opened 2017-03-21 06:40 UTC
Whenever two text fields are connected via nextNavigationField following types of log messages occur

Reading from private effective user settings.
navigationFieldDidTapNextButton: <UITextField: 0x7fb48d725cb0; frame = (0 0; 328 30); text = '100'; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x60800045aa90>; layer = <CALayer: 0x600000035a20>>
navigationFieldDidTapNextButton: <UITextField: 0x7fb48d61c780; frame = (0 0; 328 30); text = ''; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x60000025e1e0>; layer = <CALayer: 0x600000036d40>>
navigationFieldDidTapNextButton: <UITextField: 0x7fb48d6201e0; frame = (0 0; 328 30); text = ''; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x600000440ed0>; layer = <CALayer: 0x600000037b80>>
navigationFieldDidTapNextButton: <UITextField: 0x7fb48d625590; frame = (0 0; 328 30); text = ''; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x60000044a5c0>; layer = <CALayer: 0x6000000394c0>>
navigationFieldDidTapNextButton: <UITextField: 0x7fb48d628c40; frame = (0 0; 328 30); text = ''; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x60000044d2f0>; layer = <CALayer: 0x60000003a320>>
navigationFieldDidTapNextButton: <UITextField: 0x7fb48d628c40; frame = (0 0; 328 30); text = ''; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x60000044d2f0>; layer = <CALayer: 0x60000003a320>>
Though no problem with running of app is found but why this log message appears should be investigated.
Thanks

**Comment by T-Pham** [comment] 2017-03-21 08:55
Hey @nikhilpandey4, thanks for opening this issue here.
May I know what iOS version you was on when you get this issue?

**Comment by nikhilpandey4** [comment] 2017-03-21 11:08
Dear Pham,
Thanks for your message. The version I am using is 10.2.

Regards
Nikhil
Mobile : +91 9820731097
Sent from my iPhone

On 21-Mar-2017, at 2:25 PM, Thanh Pham <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @nikhilpandey4<https://github.com/nikhilpandey4>, thanks for opening this issue here.
May I know what iOS version you was on when you get this issue?

**Comment by T-Pham** [comment] 2017-03-21 16:37
Actually, it seems like you got the message when running your app in the iOS simulator.

The message "Reading from private effective user settings." is likely from the iOS SDK and not from this library at all.

For the rest of the message, "navigationFieldDidTapNextButton: ....", please check your code, it must print the string out somewhere somehow. Search for `print("navigationFieldDidTapNextButton:` in your whole project to see if there is any result.

Just FYI, I don't leave any `print` statement in the library code. I do leave some` print` statements in the Example app though.

**Comment by nikhilpandey4** [comment] 2017-03-22 01:21
Surprisingly I get this message only if I add your library , if I remove it the message disappears. This in no way as of now is causing any performance issue but am just curious why this.

Regards
Nikhil
Mobile : +91 9820731097
Sent from my iPhone

On 21-Mar-2017, at 10:07 PM, Thanh Pham <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems like you got the message when running your app in the iOS simulator.

Anyway, this message could be from the iOS SDK and not from this library at all.

**Comment by T-Pham** [comment] 2017-03-22 02:12
IMHO, just because of the message appears only when this library is added doesn't mean the message comes from this library. This message is built for UITextField and UITextView which are from the iOS SDK and your code has to be changed to adopt this library as well.

There are reports that interacting with UITextField somehow produces the message "Reading from private effective user settings."
And I guess the "navigationFieldDidTapNextButton:" part is from your code in the delegate for this library.

Anyway, since it does not affect the performance in anyway as per your input, I will close the issue for now. I am more than willing to re-open it whenever it can be proved to be caused by this library.

Have a nice day ahead!

**Closed as completed** 2017-03-22 02:13 UTC

**Comment by nikhilpandey4** [comment] 2017-03-22 04:35
Hi Pham
Thanks for your mail and sorry for writing bad English. I will check textfields and text views in my  app and try the figure out the root cause of this log message.

Regards
Nikhil
Mobile : +91 9820731097
Sent from my iPhone

On 22-Mar-2017, at 7:43 AM, Thanh Pham <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #8<https://github.com/T-Pham/UITextField-Navigation/issues/8>.
